### ISSUE TITLE
Priors *and* Parameter Constraints

### ISSUE THREAD

**Issue by iancrossfield** [MinntLeaf/TransitCurveFitter#3]
The current code won't let us both (i) use Gaussian Priors as constraints on our model parameters, and (ii) use lmfit.Model() objects so that we can get uncertainties on our best-fit parameters.

**Comment by iancrossfield** [comment]
@MinntLeaf : 
it might be a bit messy but a possible solution may be suggested here:
https://groups.google.com/g/lmfit-py/c/Gzd-DK8Prww

Specifically, we would fit with `lmfit.Model` objects but with the following changes:
1. append the desired prior values to the end of the DataY vector
2. append 1/uncertainties of each prior term (or zeros for terms set to 'None,' as currently) to the end of the DataERROR vector. 
3. In your `LmfitInputFunction`, append the values of the parameters currently being tested to the end of the 'flux' array.

Then the `lmfit.Model` fitting process should just (internally, hidden) calculate chi-squared as normal --- but it will also calculate a penalty term for each parameter, as ((tested_value - prior_value) / prior_width)**2, thus effectively including a Gaussian prior in the calculation.

so we might have:
```
# Up in the top of the Python file, create a Dictionary of priors:
ParamNames = 't0', 'per', 'rp', 'a', 'inc', 'ecc', 'w', 'u1', 'u2'
PriorsDict = dict()
for name, prior in zip(ParamNames, Priors):
    PriorsDict[name] = prior

...

# Define new DataY and DataERROR vectors:
NewPriorValues = []
NewPriorUncertainties = []
for ParamName in PriorsDict.keys():
    NewPriorValues.append(PriorsDict[ParamName][0])
    if PriorsDict[ParamName][1] is None:
        NewPriorUncertainties.append(0)
    else:
        NewPriorUncertainties.append(PriorsDict[ParamName][1])

DataYwithPriors = np.concatenate((DataY, NewPriorValues))
DataERRORwithPriors = np.concatenate((DataERROR, NewPriorUncertainties))

...

# and then change the end of LmfitInputFunction() to:
flux = m.light_curve(FittingTransityFunctionParams)
currentParamValues = [t0, per, rp, a, inc, ecc, w, u1, u2]  # Be sure the order stays consistent!
fluxwithParams = np.concatenate((flux, currentParamValues))
return(fluxwithParams)

```


Whew! Anyway, give it a try. It will be a kludge but might do the trick.

**Comment by MinntLeaf** [comment]
I added priors with a method almost identical to the above explanation. Priors are not referenced using the dictionary throughout all of the code, but I will add that later if needed.
